apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-secret.yml
  - db-CIP.yml
  - mc-CIP.yml
  - mcdep.yml
  - rmq-CIP-service.yml
  - rmq-dep.yml
  - vproapp-service.yml
  - vproappdep.yml
  - vprodbdep.yml
  - vproingress.yaml
